config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :sources

  resources :precedents

  resources :politicians

  root 'welcome#index'

end

app/models/politician.rb
class Politician < ActiveRecord::Base
    has_and_belongs_to_many :precedents
end

app/models/politicians_precedent.rb
class PoliticiansPrecedent < ActiveRecord::Base
  belongs_to :politician
  belongs_to :precedent
end

app/models/politicians_precedents.rb
class PoliticiansPrecedents < ActiveRecord::Base
  belongs_to :politician
  belongs_to :precedent
end

app/models/precedent.rb
class Precedent < ActiveRecord::Base
  has_and_belongs_to_many :politicians, auto_save: true
  has_and_belongs_to_many :sources, auto_save: true

  accepts_nested_attributes_for :politicians,
                                allow_destroy: true, 
                                reject_if: proc { |a| a[:name].blank? }
  accepts_nested_attributes_for :sources,
                                allow_destroy: true, 
                                reject_if: proc { |a| a[:url].blank? }

  validates :title, presence: true
end

app/models/precedents_source.rb
class PrecedentsSource < ActiveRecord::Base
  belongs_to :precedent
  belongs_to :source
end

app/models/precedents_sources.rb
class PrecedentsSources < ActiveRecord::Base
  belongs_to :precedent
  belongs_to :source
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_and_belongs_to_many :precedents

  validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  before_action :set_politician, only: [:show, :edit, :update, :destroy]

  # GET /politicians
  # GET /politicians.json
  def index
    @politicians = Politician.all
  end

  # GET /politicians/1
  # GET /politicians/1.json
  def show
  end

  # GET /politicians/new
  def new
    @politician = Politician.new
  end

  # GET /politicians/1/edit
  def edit
  end

  # POST /politicians
  # POST /politicians.json
  def create
    @politician = Politician.new(politician_params)

    respond_to do |format|
      if @politician.save
        format.html { redirect_to @politician, notice: 'Politician was successfully created.' }
        format.json { render :show, status: :created, location: @politician }
      else
        format.html { render :new }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /politicians/1
  # PATCH/PUT /politicians/1.json
  def update
    respond_to do |format|
      if @politician.update(politician_params)
        format.html { redirect_to @politician, notice: 'Politician was successfully updated.' }
        format.json { render :show, status: :ok, location: @politician }
      else
        format.html { render :edit }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politicians/1
  # DELETE /politicians/1.json
  def destroy
    @politician.destroy
    respond_to do |format|
      format.html { redirect_to politicians_url, notice: 'Politician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politician
      @politician = Politician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def politician_params
      params.require(:politician).permit(:name, :lastname)
    end
end

app/controllers/precedents_controller.rb
class PrecedentsController < ApplicationController
  before_action :set_precedent, only: [:show, :edit, :update, :destroy]

  # GET /precedents
  # GET /precedents.json
  def index
    @precedents = Precedent.all.order(created_at: :desc).limit(9)
  end

  # GET /precedents/1
  # GET /precedents/1.json
  def show
  end

  # GET /precedents/new
  def new
    @precedent = Precedent.new
  end

  # GET /precedents/1/edit
  def edit
  end

  # POST /precedents
  # POST /precedents.json
  def create
    @precedent = Precedent.new(precedent_params)

    respond_to do |format|
      if @precedent.save
        format.html { redirect_to @precedent, notice: 'Precedent was successfully created.' }
        format.json { render :show, status: :created, location: @precedent }
      else
        format.html { render :new }
        format.json { render json: @precedent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /precedents/1
  # PATCH/PUT /precedents/1.json
  def update
    respond_to do |format|
      if @precedent.update(precedent_params)
        format.html { redirect_to @precedent, notice: 'Precedent was successfully updated.' }
        format.json { render :show, status: :ok, location: @precedent }
      else
        format.html { render :edit }
        format.json { render json: @precedent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /precedents/1
  # DELETE /precedents/1.json
  def destroy
    @precedent.destroy
    respond_to do |format|
      format.html { redirect_to precedents_url, notice: 'Precedent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_precedent
      @precedent = Precedent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def precedent_params
      params.require(:precedent)
            .permit(:title, :description,
                    sources_attributes: [:id, :url, :_destroy],
                    politicians_attributes: [:id, :name, :lastname, :_destroy])
    end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]

  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to @source, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'Source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/helpers/precedents_helper.rb
module PrecedentsHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Historial de políticos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">

    <div class="container">
    
      <div class="navbar-brand">
        <%= link_to "Historial de políticos", root_path %>
      </div>  <!-- navbar-brand -->

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New precedent", new_precedent_path %></li>
        <li><%= link_to "Sign in", root_path %></li>
      </ul>  <!-- nav navbar-nav navbar-right -->

    </div>  <!-- container -->

  </nav>  <!-- navbar navbar-default -->

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert" %>
    <% end %>

    <%= yield %>
  </div>  <!-- .container -->

</body>
</html>

app/views/politicians/_form.html.erb
<%= form_for(@politician) do |f| %>
  <% if @politician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@politician.errors.count, "error") %> prohibited this politician from being saved:</h2>

      <ul>
      <% @politician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/politicians/edit.html.erb
<h1>Editing Politician</h1>

<%= render 'form' %>

<%= link_to 'Show', @politician %> |
<%= link_to 'Back', politicians_path %>

app/views/politicians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Politicians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @politicians.each do |politician| %>
      <tr>
        <td><%= politician.name %></td>
        <td><%= politician.lastname %></td>
        <td><%= link_to 'Show', politician %></td>
        <td><%= link_to 'Edit', edit_politician_path(politician) %></td>
        <td><%= link_to 'Destroy', politician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Politician', new_politician_path %>

app/views/politicians/new.html.erb
<h1>New Politician</h1>

<%= render 'form' %>

<%= link_to 'Back', politicians_path %>

app/views/politicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @politician.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @politician.lastname %>
</p>

<h1>Precedents</h1>

<% if @politician.precedents.blank? %>
  No precedents registered
<% else %>
  <% for precedent in @politician.precedents %>
    <ul>
      <li><%= link_to "#{precedent.title}", precedent %></li>
    </ul>
  <% end %>
<% end %>

<h1>Statistics</h1>

<ul>
  <li>Total precedents: <%= @politician.precedents.size %></li>
</ul>

<%= link_to 'Edit', edit_politician_path(@politician) %> |
<%= link_to 'Back', politicians_path %>

app/views/precedents/_form.html.erb
<%= form_for(@precedent) do |f| %>
  <% if @precedent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@precedent.errors.count, "error") %> prohibited this precedent from being saved:</h2>

      <ul>
      <% @precedent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel-body">

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>

    <div class="row">
      <div class="col-md-6">
        <h3>Sources</h3>
        <div id="sources">
          <%= f.fields_for :sources do |source| %>
            <%= render 'source_fields', :f => source %>
          <% end %>

          <div class="links">
            <%= link_to_add_association 'Add source', f, :sources, class: 'btn btn-default add-button' %>
          </div>
        </div>
        
      </div>

      <div class="col-md-6">
        <h3>Politicians</h3>
        <div id="politicians">
          <%= f.fields_for :politicians do |politician| %>
            <%= render 'politician_fields', :f => politician %>
          <% end %>

          <div class="links">
            <%= link_to_add_association 'Add politician', f, :politicians, class: 'btn btn-default add-button' %>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/precedents/_politician_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= link_to_remove_association "Remove politician", f, class: "form-button btn btn-default" %>
</div>

app/views/precedents/_source_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <%= link_to_remove_association "Remove source", f, class: "form-button btn btn-default" %>
</div>

app/views/precedents/edit.html.erb
<h1>Editing Precedent</h1>

<%= render 'form' %>

<%= link_to 'Show', @precedent %> |
<%= link_to 'Back', precedents_path %>

app/views/precedents/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar options">
  <ul>
    <%= link_to 'New Precedent', new_precedent_path, class: "btn btn-default" %>
  </ul>
</nav>

<% @precedents.each_slice(3) do |precedents| -%>
<div class="row">
  <% precedents.each do |precedent| -%>
  <div class="col-md-4">
    <div class="precedent">
      <%= precedent.title %>
      <div class="options">
        <%= link_to 'Show', precedent, class: "btn btn-default" %>
        <%= link_to 'Edit', edit_precedent_path(precedent), class: "btn btn-default" %>
        <%= link_to 'Destroy', precedent, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <% end -%>
</div>
<% end -%>

app/views/precedents/new.html.erb
<h1>New Precedent</h1>

<%= render 'form' %>

<%= link_to 'Back', precedents_path %>

app/views/precedents/show.html.erb
<p id="notice"><%= notice %></p>

<div class="main-content">

  <div id="precedent_top" class="row">
    <div class="col-md-4">
      :)
    </div>

    <div class="col-md-4">
      <div id="precedent_info">
        <h1><%= @precedent.title %></h1>
        <p class="description"><%= @precedent.description %></p>
      </div>
    </div>
  </div>  <!-- #precedent_top.row -->

  <div class="row">
    <div class="col-md-6">
      <div id="politicians">
        <h2>Politicians</h2>
        <% if @precedent.politicians.blank? %>
          No politicians involved
        <% else %>
          <ul>
            <% @precedent.politicians.each do |politician| -%>
            <li><%= link_to politician.name, politician %></li>
            <% end -%>
          </ul>
        <% end -%>
      </div>  <!-- #politicians -->
    </div>

    <div class="col-md-6">
      <div id="sources">
        <h2>Sources</h2>
        <% if @precedent.sources.blank? %>
          No sources registered
        <% else %>
          <ul>
            <% @precedent.sources.each do |source| -%>
            <li><%= link_to source.url, source %></li>
            <% end -%>
          </ul>
        <% end -%>
      </div>  <!-- #sources -->
    </div>

  </div>

  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Edit', edit_precedent_path(@precedent), class: "btn btn-default" %>
      <%= link_to 'Back', precedents_path, class: "btn btn-default" %>
      <%= link_to 'Delete', precedents_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default" %>      
    </div>
  </div>

</div>

app/views/sources/_form.html.erb
<%= form_for(@source) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Editing Source</h1>

<%= render 'form' %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sources</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sources.each do |source| %>
      <tr>
        <td><%= source.url %></td>
        <td><%= link_to 'Show', source %></td>
        <td><%= link_to 'Edit', edit_source_path(source) %></td>
        <td><%= link_to 'Destroy', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source', new_source_path %>

app/views/sources/new.html.erb
<h1>New Source</h1>

<%= render 'form' %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @source.url %>
</p>

<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>